
	[constants]
	RoleAdmin = "Administrator"
	RoleReceptionist = "Receptionist"

	StatusCreated = 201
	StatusBadRequest = 400
	StatusUnauthorized = 401
	StatusForbidden = 403
	StatusInternalServerError = 500

	MongoDBURI = "mongodb://localhost:27017"
	MongoDBDatabase = "testdb"
	FrontendURL = "http://localhost:3000"

	CollectionUsers = "users"
	CollectionValidCURPs = "valid_curps"

	JWTSecretKey = "my_secret_key"

	ServerAddress = "0.0.0.0"
	ServerPort = "8000"
	
	CloudinaryCloudName = "your-cloudinary-cloud-name"
	CloudinaryAPIKey = "your-cloudinary-api-key"
	CloudinaryAPISecret = "your-cloudinary-api-secret"
	GoogleDriveFolderID = "1jksEqpqaKbf_bU-ZdxJiBX_4HFhr1Bj_"
	GoogleDriveCredentialsPath = "credentials.json"